source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5'
gem 'redis', '~> 3.1.0'
gem 'httparty'

# only used locally in development
group :development do
  gem 'pry'
  gem 'shotgun'
end

group :production do

end
